proj1 <- read.table("household_power_consumption.txt",header=TRUE,sep=";",stringsAsFactors=FALSE)
proj1 <- subset(proj1, Date=="1/2/2007" | Date=="2/2/2007")
Sys.setlocale(category = "LC_TIME", locale = "C")
proj1$Global_active_power <- as.numeric(proj1$Global_active_power)
png(file = "plot1.png",width = 480, height = 480, units = "px") 
hist(proj1$Global_active_power,col="red",main="Global Active Power",xlab="Global Active Power (kilowatts)")
dev.off() 