proj1 <- read.table("household_power_consumption.txt",header=TRUE,sep=";",stringsAsFactors=FALSE)
proj1 <- subset(proj1, Date=="1/2/2007" | Date=="2/2/2007")
Sys.setlocale(category = "LC_TIME", locale = "C")
png(file = "plot3.png",width = 480, height = 480, units = "px") 
plot(strptime(paste(proj1$Date, proj1$Time), format = "%d/%m/%Y %H:%M:%S"),proj1$Sub_metering_1,type="l",ylab="Energy sub metering",xlab=" ")
lines(strptime(paste(proj1$Date, proj1$Time), format = "%d/%m/%Y %H:%M:%S"),proj1$Sub_metering_2, type="l",col="red")
lines(strptime(paste(proj1$Date, proj1$Time), format = "%d/%m/%Y %H:%M:%S"),proj1$Sub_metering_3, type="l",col="blue")
legend("topright",bty="n",lwd=1,col=c("black","red","blue"),legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off() 