proj1 <- read.table("household_power_consumption.txt",header=TRUE,sep=";",stringsAsFactors=FALSE)
proj1 <- subset(proj1, Date=="1/2/2007" | Date=="2/2/2007")
proj1$Global_active_power <- as.numeric(proj1$Global_active_power)
proj1$Voltage <- as.numeric(proj1$Voltage)
Sys.setlocale(category = "LC_TIME", locale = "C")
png(file = "plot4.png",width = 480, height = 480, units = "px")
par(mfrow=c(2,2))
plot(strptime(paste(proj1$Date, proj1$Time), format = "%d/%m/%Y %H:%M:%S"),proj1$Global_active_power,type="l",ylab="Global Active Power (kilowatts)",xlab=" ")
plot(strptime(paste(proj1$Date, proj1$Time), format = "%d/%m/%Y %H:%M:%S"),proj1$Voltage,type="l",ylab="Global Active Power (kilowatts)",xlab="datetime")
plot(strptime(paste(proj1$Date, proj1$Time), format = "%d/%m/%Y %H:%M:%S"),proj1$Sub_metering_1,type="l",ylab="Energy sub metering",xlab=" ")
lines(strptime(paste(proj1$Date, proj1$Time), format = "%d/%m/%Y %H:%M:%S"),proj1$Sub_metering_2, type="l",col="red")
lines(strptime(paste(proj1$Date, proj1$Time), format = "%d/%m/%Y %H:%M:%S"),proj1$Sub_metering_3, type="l",col="blue")
legend("topright",bty="n",lwd=1,col=c("black","red","blue"),legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
plot(strptime(paste(proj1$Date, proj1$Time), format = "%d/%m/%Y %H:%M:%S"),proj1$Global_reactive_power,type="l",ylab="Global_reactive_power",xlab="datetime")
dev.off()